In [1]:
#pip install  numpy

     |████████████████████████████████| 17.0 MB 1.6 MB/s 
You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
#Creaate a 1D array of numbers from  0 to 9
array1 = np.array([1,2,3,4,5,6,7,8,9])
print(array1)

[1 2 3 4 5 6 7 8 9]


In [4]:
#Create a  1D array of numbers from 0 to 9
#using np.arange
arr = np.arange(0,9)
print(arr)

[0 1 2 3 4 5 6 7 8]


In [8]:
#Create a 3*3 Numpy array of all Boolean value Trues
arr3=[[4,5,6],[7,8,9],[10,11,12]]
arra=np.array(arr3)
y= arra > 3
print(y)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [18]:
#Extract all odd numbers from array of 1-10
#Using   np.arange
arr2=np.arange(1,10)
print(arr2)

arr2[::2]


[1 2 3 4 5 6 7 8 9]


array([1, 3, 5, 7, 9])

In [19]:
#Replace all odd numbers in an array of 1-10 with value -1
#Using np.arange
arr4=np.arange(1,10)
arr4[::2]= -1
print(arr4)

[-1  2 -1  4 -1  6 -1  8 -1]


In [20]:
#Convert a 1D  array to a 2D array with 2 rows
arr1 = np.array([2,4,6,8,10,12,14,16])
newarr1 = arr1.reshape(2,4)
print(newarr1)

[[ 2  4  6  8]
 [10 12 14 16]]


In [23]:
#Create two arrays a and b
#stack these two arrays vertically
#using the np.dot and np.sum to calculate totals
a=np.array([4,5,6])
b=np.array([8,10,12])
arry1=np.vstack((a,b))
print(arry1)


c=np.dot(a,b)
print(c)

totalsum=np.sum(c)
print(totalsum)

[[ 4  5  6]
 [ 8 10 12]]
154
154


In [24]:

my_file=open("Numbers","w")
my_file.close()

In [39]:
#creating a file name Numbers

my_file=open("Numbers.txt", "w")
my_file.close()


In [42]:
#Write a program  that allows you to enter 4 numbers and stores them in a file called Numbers
#Writing "w"
n1=(3)
n2=(45)
n3=(83)
n4=(21)

my_file = open("Numbers.txt","w")
my_file.write(str(n1)+ "\n")
my_file.write(str(n2)+  "\n")
my_file.write(str(n3)+ "\n")
my_file.write(str(n4)+ "\n")

my_file.close()


In [43]:
#Appending "a"

my_file = open("Numbers.txt","a")

my_file.write("I love python  coding.\n")

my_file.close()

In [44]:
#Reading "r"
with open("Numbers.txt","r")  as myfile:
    Da1 = myfile.read().replace('\n',',')

myfile.close()

print(Da1)



3,45,83,21,I love python  coding.,
